spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    baseline-on-migrate: true
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 6064